name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:

jobs:
  lint:
    name: SwiftLint (macOS)
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install SwiftLint
        run: brew install swiftlint

      - name: Run SwiftLint
        run: swiftlint

  build-and-test:
    name: Build & Test (Ubuntu + Swift 6.1)
    runs-on: ubuntu-22.04

    env:
      SWIFT_VERSION: "6.1"
      SWIFT_PLATFORM: "ubuntu22.04"
      SWIFT_URL: "https://download.swift.org/swift-6.1-release/ubuntu2204/swift-6.1-RELEASE/swift-6.1-RELEASE-ubuntu22.04.tar.gz"
      SWIFT_DIR: "$HOME/swift-6.1"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            clang \
            libicu-dev \
            libpython3-dev \
            libncurses5 \
            libcurl4 \
            libedit2 \
            libxml2 \
            libsqlite3-0 \
            pkg-config \
            tzdata \
            git

      - name: Download and install Swift ${{ env.SWIFT_VERSION }}
        run: |
          mkdir -p $SWIFT_DIR
          curl -sL $SWIFT_URL | tar -xz --strip-components=1 -C $SWIFT_DIR
          echo "$SWIFT_DIR/usr/bin" >> $GITHUB_PATH

      - name: Check Swift version
        run: swift --version

      - name: Build in release configuration
        run: swift build -c release

      - name: Run tests
        run: swift test --enable-code-coverage
